### PR TITLE
Guided Synthesis

### PR DESCRIPTION
**Pull request by Patchethium**
## 内容

GUI implementation for [Guide Synthesis](https://github.com/VOICEVOX/voicevox_engine/pull/252) API of engine.

It's worth noting that I was using the branch [here](https://github.com/VOICEVOX/voicevox_engine/pull/376), which is not yet merged into `master`.

Still a WIP for there's a lot to do.

## スクリーンショット・動画など

https://user-images.githubusercontent.com/74458240/159207299-8685ad47-17b0-45eb-9e27-9f4d7ca4671f.mp4

### CODE REVIEW

**Comment by Patchethium** [comment]
I guess that's all, tell me if you find any problems.
(And anyone kind enough to translate the texts for me is welcomed.)

**Comment by Patchethium** [comment]
Updated with [engine](https://github.com/VOICEVOX/voicevox_engine/pull/376).

**Comment by Hiroshiba** [comment]
The API on the engine side has changed, so OpenAPI may need to follow suit. :-)

**Comment by Patchethium** [comment]
It's already updated in 8622238.

**Comment by Hiroshiba** [comment]
Oh, sorry!!!

**Comment by Patchethium** [comment]
Resolved conflicts. And it's worth noting that since I started using `pnpm` there's a newly added `pnpm-lock.yaml` config file. It doesn't influence the original `npm`.

**Comment by Patchethium** [comment]
Nah nevermind, `pnpm` doesn't support node 14.

**Comment by Patchethium** [comment]
> もしかしたら、windowsのパス（バックスラッシュ）がうまくいかない原因かも･･･？

No, it works like a charm on my Windows machine.

Maybe you forgot to add "--enable_guided" into engine's command line parameters, which is introduced since the discussion [here](https://github.com/VOICEVOX/voicevox_engine/pull/252#discussion_r820820889). Sorry I didn't mention it earlier.

**Comment by Patchethium** [comment]
Oh no, I just found that nuitka breaks this feature in the released binaries, I need to find a work around.
If you're using the complied one, I suggest you to launch it from source instead or just wait until I fix this nuitka problem.

Of course before I fixed the engine don't approve this pr, but you can still leave some review.

**Comment by Patchethium** [comment]
I surrender. Even installing a new virtual machine doesn't get the engine to compile locally, which leads my decision on giving up this feature and grab sth more enjoyable than fighting with dependencies.
I'll soon push a revert pr on the engine repo.

**Pull request closed without merging**
